classdef (Enumeration) TYP_CSW_INT_POSITION < Simulink.IntEnumType
  enumeration
    CSW_INTERMITTENT_POSITION_1(0)
    CSW_INTERMITTENT_POSITION_2(1)
    CSW_INTERMITTENT_POSITION_3(2)
    CSW_INTERMITTENT_POSITION_4(3)
    CSW_INTERMITTENT_POSITION_5(4)
    CSW_INTERMITTENT_POSITION_6(5)
    CSW_INTERMITTENT_POSITION_7(6)
    CSW_INTERMITTENT_POSITION_8(7)
  end
end  
